---
name: Release

on:
  push:
    tags:
      - v**

jobs:
  auto-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

